### ISSUE TITLE
Implement List collection

### ISSUE THREAD

**Issue by architagr** [architagr/golang_collections#9]
Basic operations to be supported:

1. Add
2. AddRange
3. Where - to help filter list based on the comparator function been passed
4. Skip - to skip first n values from the list (to help pagination)
5. Take - to take first n value from the list (to help pagination)
6. First - to get first value that matched the condition in the comparator function been passed
7. Remove - to remove mentioned index 
8. IndexOf - get index of the first element that matched the condition in the comparator function been passed

**Comment by yimikao** [comment]
Hi @architagr can i pick this up

**Comment by architagr** [comment]
Sure
